### ISSUE TITLE
🎮 示例相关 | 能否提供一个演示的账号？想看一下你的权限呈现方式

### ISSUE THREAD

**Issue by lytdev** [d2-projects/d2-admin-xiya-go-cms#17]
我最近参考你的项目也做了一个权限控制的前端，但是在加载侧边栏和多标签栏时，出现了不联动和侧边栏不激活的BUG，我想看下是我的权限格式设置错误还是d2admin的BUG

**Comment by FairyEver** [comment]
现在已经公开账号 见 README
