### ISSUE TITLE
# index 最小的地址被默认激活 VUE_APP_API

### ISSUE THREAD

**Issue by zeng-yang** [d2-projects/d2-admin-xiya-go-cms#23]
# index 最小的地址被默认激活
VUE_APP_API_1_TEST=https://api.cms.xiya.vip
VUE_APP_API_0_DEV=http://127.0.0.1:8888
修改后无效，还是默认激活https://api.cms.xiya.vip

**Comment by FairyEver** [comment]
清空 localstorage 后刷新页面
